version: '3.3'
services:
  employee-mgmt-service:
    container_name: employee-mgmt-service
    build: employee-mgmt-service
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
    depends_on:
        - employee-service
  employee-service:
    container_name: employee-service
    build: employee-service
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
